allowBuilds:
  cbor-extract: false
  esbuild: false

overrides:
  "@inkandswitch/patchwork-providers": "file:../../patchwork-next/dist/inkandswitch-patchwork-providers-0.0.0.tgz"
  "@patchwork/solid": "file:../../patchwork-next/dist/patchwork-solid-1.0.0.tgz"
