allowBuilds:
  cbor-extract: false
  esbuild: false
minimumReleaseAge: 0
verifyDepsBeforeRun: false
overrides:
  "@inkandswitch/patchwork-providers": "file:../../patchwork-next/packages/providers/core/dist/inkandswitch-patchwork-providers-0.2.2.tgz"
  "@inkandswitch/patchwork-providers-solid": "file:../../patchwork-next/packages/providers/frameworks/solid/dist/inkandswitch-patchwork-providers-solid-0.2.3.tgz"
  "@inkandswitch/patchwork-elements": "file:../../patchwork-next/core/elements/dist/inkandswitch-patchwork-elements-1.0.0.tgz"
