// Extension to MIME type mapping

const mimeTypes: Record<string, string> = {
	".js": "application/javascript",
	".mjs": "application/javascript",
	".cjs": "application/javascript",
	".jsx": "application/javascript",
	".ts": "text/typescript",
	".mts": "text/typescript",
	".cts": "text/typescript",
	".tsx": "text/typescript",
	".css": "text/css",
	".html": "text/html",
	".htm": "text/html",
	".json": "application/json",
	".jsonc": "application/json",
	".md": "text/markdown",
	".markdown": "text/markdown",
	".mdx": "text/markdown",
	".py": "text/x-python",
	".xml": "text/xml",
	".svg": "image/svg+xml",
	".yaml": "text/yaml",
	".yml": "text/yaml",
	".rs": "text/x-rustsrc",
	".c": "text/x-csrc",
	".h": "text/x-csrc",
	".cpp": "text/x-c++src",
	".hpp": "text/x-c++src",
	".cc": "text/x-c++src",
	".cxx": "text/x-c++src",
	".java": "text/x-java",
	".php": "text/x-php",
	".sql": "text/x-sql",
	".wat": "text/x-wast",
	".wast": "text/x-wast",
	".txt": "text/plain",
	".csv": "text/csv",
	".tsv": "text/tab-separated-values",
	".sh": "text/x-shellscript",
	".bash": "text/x-shellscript",
	".zsh": "text/x-shellscript",
	".toml": "text/x-toml",
	".ini": "text/x-ini",
	".log": "text/plain",
	".env": "text/plain",
	".png": "image/png",
	".jpg": "image/jpeg",
	".jpeg": "image/jpeg",
	".gif": "image/gif",
	".webp": "image/webp",
	".pdf": "application/pdf",
}

export function getMimeType(extension: string): string {
	const ext = extension.startsWith(".") ? extension : `.${extension}`
	return mimeTypes[ext] || "text/plain"
}
